---
version: "3"

vars:
  DB: ""
  CONFIG: ""

tasks:
  init-tools:
    dir: tools
    cmds:
      - go mod tidy
      - go mod verify
      - go generate -x

  init:
    desc: "Install development tools"
    deps: [init-tools]
    cmds:
      - go mod tidy
      - go mod verify

  fmt:
    desc: "Format code"
    cmds:
      - bin/gofumpt -w ./cmd/ ./internal/

  env-up:
    desc: "Start environment"
    deps: [env-up-detach]
    cmds:
      - docker compose logs --follow

  env-up-detach:
    desc: "Start dependencies in docker"
    cmds:
      # use -t instead of --timeout / --wait-timeout to be compatible with all versions:
      # https://github.com/docker/compose/issues/10269#issuecomment-1495205234
      - >
        docker compose up --always-recreate-deps --force-recreate --remove-orphans --renew-anon-volumes -t 0 --detach
        --build {{.DB}}
      # - task: init-repl
      # - task: init-user

  env-pull:
    cmds:
      - docker compose pull
      - docker compose build --pull

  env-logs:
    cmds:
      - docker compose ps --all
      - docker compose logs --follow

  env-logs-collect:
    cmds:
      - docker compose ps --all
      - docker compose logs

  env-down:
    desc: "Stop environment"
    cmds:
      - docker compose down --remove-orphans --volumes

  build:
    desc: "Build dance tool"
    cmds:
      - go build -v -o bin/ ./cmd/dance/

  dance:
    desc: "Dance!"
    deps: [build]
    dir: projects
    cmds:
      - ../bin/dance --database={{.DB}} {{.CONFIG}}

  lint:
    desc: "Run linters"
    cmds:
      - >
        bin/golangci-lint run --config=.golangci.yml
        ./cmd/... ./internal/... ./projects/mongo-tools/...
      - >
        bin/golangci-lint run --config=.golangci-new.yml
        ./cmd/... ./internal/... ./projects/mongo-tools/...
      - >
        bin/go-consistent -pedantic
        ./cmd/... ./internal/... ./projects/mongo-tools/...

  psql:
    desc: "Run psql"
    cmds:
      - docker compose exec postgres psql -U postgres -d ferretdb

  mongo:
    desc: "Run legacy MongoDB shell (`mongo`) with test script"
    cmds:
      - >
        docker compose run --rm mongo
        'mongodb://host.docker.internal:27017/'
        {{.CLI_ARGS}}

  mongosh:
    desc: "Run mongo shell"
    cmds:
      - >
        docker compose run --rm mongosh mongosh
        'mongodb://host.docker.internal:27017/'
        --eval 'disableTelemetry()' --shell

  init-repl:
    desc: "Initializes a new replica set"
    cmds:
      - >
        docker compose run --rm mongosh mongosh
        'mongodb://host.docker.internal:27017/'
        --verbose --eval 'rs.initiate({_id: "rs0", members: [{_id: 0, host: "localhost"}]})'
    # ignore already initialized error and no such command error for replSetInitiate
    ignore_error: true

  # creates a user similar to MONGO_INITDB_ROOT_USERNAME but does not enable authentication
  # https://github.com/docker-library/mongo/blob/master/7.0/docker-entrypoint.sh#L260
  init-user:
    desc: "Creates a user with the root access role"
    cmds:
      - >
        docker compose run --rm mongosh mongosh
        'mongodb://host.docker.internal:27017/'
        --verbose --eval 'db.getSiblingDB("admin").createUser({user: "user", pwd: "password", roles: [ "root" ]})'
    # ignore roles that are not implemented yet
    ignore_error: true

  godocs:
    desc: "Serve Go code documentation"
    cmds:
      - bin/pkgsite{{exeExt}} -http=127.0.0.1:6060 -open

  # see https://github.com/DavidAnson/markdownlint-cli2#command-line for the reason we use double-quotes
  docs-fmt:
    desc: "Format and lint documentation"
    cmds:
      - docker compose run --rm textlint --fix --rule one-sentence-per-line "**/*.md" ".github/**/*.md"
      - docker compose run --rm markdownlint "**/*.md" "#dumps" "#projects"
