---
name: Linters
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - unlabeled # if GitHub Actions stuck, add and remove "not ready" label to force rebuild
      - opened
      - reopened
      - synchronize
  schedule:
    - cron: "12 3 * * *"

# Do not run this job in parallel for any PR change or branch push.
concurrency:
  group: ${{ github.workflow }}-golangci-lint-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

env:
  GOPATH: /home/runner/go
  GOCACHE: /home/runner/go/cache
  GOLANGCI_LINT_CACHE: /home/runner/go/cache/lint
  GOMODCACHE: /home/runner/go/mod
  GOPROXY: https://proxy.golang.org
  GOTOOLCHAIN: local

jobs:
  linters:
    name: linters
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    # Do not run this job in parallel for any PR change or branch push.
    concurrency:
      group: ${{ github.workflow }}-linters-${{ github.head_ref || github.ref_name }}
      cancel-in-progress: true

    if: github.event_name != 'pull_request' || !contains(github.event.pull_request.labels.*.name, 'not ready')

    steps:
      # TODO https://github.com/FerretDB/github-actions/issues/211
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # for `golangci-lint run --new` to work
          lfs: false # LFS is used only by website

      - name: Setup Go
        uses: FerretDB/github-actions/setup-go@main
        with:
          cache-key: lint

      - name: Run linters
        uses: FerretDB/github-actions/linters@main

      - name: Format and lint documentation
        run: bin/task docs-fmt
